name: DepEd Puerto Princesa City Division Official Website
favicon: null
layout_spectrum: 0.354729
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0D8C8'
    - '#904040'
    - '#788088'
    - '#B8A848'
    - '#000000'
  brandStrength: 0.010899160009636755
  lightness: 0.5078009172096415
  saturation: 0.10255708876727176
  rhythmicContrast: 0.12150658725847141
purpose:
  - name: null
    item: null
    url: null
